# Default CI workflow
# Example taken from https://github.com/actions/starter-workflows/blob/3fb9f82449706d5e8e6605bf7cb839b690359cdc/ci/dotnet.yml

name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        cache: true
        cache-dependency-path: '**/packages.lock.json'

    - name: Restore dependencies
      run: dotnet restore --locked-mode

    - name: Build project
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
